import = ["/home/phil/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "regular"

[shell]
program = "/usr/bin/bash"

[window]
#decorations = "None"
#dynamic_padding = false

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 5
y = 5
